mkdir -pv AA/AAML && wget http://files.docking.org/3D/AA/AAML/AAAAML.xaa.pdbqt.gz -O AA/AAML/AAAAML.xaa.pdbqt.gz
mkdir -pv AA/AAMM && wget http://files.docking.org/3D/AA/AAMM/AAAAMM.xaa.pdbqt.gz -O AA/AAMM/AAAAMM.xaa.pdbqt.gz
mkdir -pv AA/AAMN && wget http://files.docking.org/3D/AA/AAMN/AAAAMN.xaa.pdbqt.gz -O AA/AAMN/AAAAMN.xaa.pdbqt.gz
mkdir -pv AA/AAMO && wget http://files.docking.org/3D/AA/AAMO/AAAAMO.xaa.pdbqt.gz -O AA/AAMO/AAAAMO.xaa.pdbqt.gz
mkdir -pv AA/AAMP && wget http://files.docking.org/3D/AA/AAMP/AAAAMP.xaa.pdbqt.gz -O AA/AAMP/AAAAMP.xaa.pdbqt.gz
mkdir -pv AA/AARL && wget http://files.docking.org/3D/AA/AARL/AAAARL.xaa.pdbqt.gz -O AA/AARL/AAAARL.xaa.pdbqt.gz
mkdir -pv AA/AARM && wget http://files.docking.org/3D/AA/AARM/AAAARM.xaa.pdbqt.gz -O AA/AARM/AAAARM.xaa.pdbqt.gz
mkdir -pv AA/AARN && wget http://files.docking.org/3D/AA/AARN/AAAARN.xaa.pdbqt.gz -O AA/AARN/AAAARN.xaa.pdbqt.gz
mkdir -pv AA/AARO && wget http://files.docking.org/3D/AA/AARO/AAAARO.xaa.pdbqt.gz -O AA/AARO/AAAARO.xaa.pdbqt.gz
mkdir -pv AA/AARP && wget http://files.docking.org/3D/AA/AARP/AAAARP.xaa.pdbqt.gz -O AA/AARP/AAAARP.xaa.pdbqt.gz
mkdir -pv AA/ABML && wget http://files.docking.org/3D/AA/ABML/AAABML.xaa.pdbqt.gz -O AA/ABML/AAABML.xaa.pdbqt.gz
mkdir -pv AA/ABMM && wget http://files.docking.org/3D/AA/ABMM/AAABMM.xaa.pdbqt.gz -O AA/ABMM/AAABMM.xaa.pdbqt.gz
mkdir -pv AA/ABMN && wget http://files.docking.org/3D/AA/ABMN/AAABMN.xaa.pdbqt.gz -O AA/ABMN/AAABMN.xaa.pdbqt.gz
mkdir -pv AA/ABMO && wget http://files.docking.org/3D/AA/ABMO/AAABMO.xaa.pdbqt.gz -O AA/ABMO/AAABMO.xaa.pdbqt.gz
mkdir -pv AA/ABMP && wget http://files.docking.org/3D/AA/ABMP/AAABMP.xaa.pdbqt.gz -O AA/ABMP/AAABMP.xaa.pdbqt.gz
mkdir -pv AA/ABRL && wget http://files.docking.org/3D/AA/ABRL/AAABRL.xaa.pdbqt.gz -O AA/ABRL/AAABRL.xaa.pdbqt.gz
mkdir -pv AA/ABRM && wget http://files.docking.org/3D/AA/ABRM/AAABRM.xaa.pdbqt.gz -O AA/ABRM/AAABRM.xaa.pdbqt.gz
mkdir -pv AA/ABRN && wget http://files.docking.org/3D/AA/ABRN/AAABRN.xaa.pdbqt.gz -O AA/ABRN/AAABRN.xaa.pdbqt.gz
mkdir -pv AA/ABRO && wget http://files.docking.org/3D/AA/ABRO/AAABRO.xaa.pdbqt.gz -O AA/ABRO/AAABRO.xaa.pdbqt.gz
mkdir -pv AA/ABRP && wget http://files.docking.org/3D/AA/ABRP/AAABRP.xaa.pdbqt.gz -O AA/ABRP/AAABRP.xaa.pdbqt.gz
mkdir -pv AA/ACRN && wget http://files.docking.org/3D/AA/ACRN/AAACRN.xaa.pdbqt.gz -O AA/ACRN/AAACRN.xaa.pdbqt.gz
mkdir -pv AA/ADML && wget http://files.docking.org/3D/AA/ADML/AAADML.xaa.pdbqt.gz -O AA/ADML/AAADML.xaa.pdbqt.gz
mkdir -pv AA/ADMM && wget http://files.docking.org/3D/AA/ADMM/AAADMM.xaa.pdbqt.gz -O AA/ADMM/AAADMM.xaa.pdbqt.gz
mkdir -pv AA/ADMN && wget http://files.docking.org/3D/AA/ADMN/AAADMN.xaa.pdbqt.gz -O AA/ADMN/AAADMN.xaa.pdbqt.gz
mkdir -pv AA/ADMO && wget http://files.docking.org/3D/AA/ADMO/AAADMO.xaa.pdbqt.gz -O AA/ADMO/AAADMO.xaa.pdbqt.gz
mkdir -pv AA/ADMP && wget http://files.docking.org/3D/AA/ADMP/AAADMP.xaa.pdbqt.gz -O AA/ADMP/AAADMP.xaa.pdbqt.gz
mkdir -pv AA/ADRL && wget http://files.docking.org/3D/AA/ADRL/AAADRL.xaa.pdbqt.gz -O AA/ADRL/AAADRL.xaa.pdbqt.gz
mkdir -pv AA/ADRM && wget http://files.docking.org/3D/AA/ADRM/AAADRM.xaa.pdbqt.gz -O AA/ADRM/AAADRM.xaa.pdbqt.gz
mkdir -pv AA/ADRN && wget http://files.docking.org/3D/AA/ADRN/AAADRN.xaa.pdbqt.gz -O AA/ADRN/AAADRN.xaa.pdbqt.gz
mkdir -pv AA/ADRO && wget http://files.docking.org/3D/AA/ADRO/AAADRO.xaa.pdbqt.gz -O AA/ADRO/AAADRO.xaa.pdbqt.gz
mkdir -pv AA/ADRP && wget http://files.docking.org/3D/AA/ADRP/AAADRP.xaa.pdbqt.gz -O AA/ADRP/AAADRP.xaa.pdbqt.gz
mkdir -pv AA/BAMM && wget http://files.docking.org/3D/AA/BAMM/AABAMM.xaa.pdbqt.gz -O AA/BAMM/AABAMM.xaa.pdbqt.gz
mkdir -pv AA/BAMN && wget http://files.docking.org/3D/AA/BAMN/AABAMN.xaa.pdbqt.gz -O AA/BAMN/AABAMN.xaa.pdbqt.gz
mkdir -pv AA/BAMO && wget http://files.docking.org/3D/AA/BAMO/AABAMO.xaa.pdbqt.gz -O AA/BAMO/AABAMO.xaa.pdbqt.gz
mkdir -pv AA/BARL && wget http://files.docking.org/3D/AA/BARL/AABARL.xaa.pdbqt.gz -O AA/BARL/AABARL.xaa.pdbqt.gz
mkdir -pv AA/BARM && wget http://files.docking.org/3D/AA/BARM/AABARM.xaa.pdbqt.gz -O AA/BARM/AABARM.xaa.pdbqt.gz
mkdir -pv AA/BARN && wget http://files.docking.org/3D/AA/BARN/AABARN.xaa.pdbqt.gz -O AA/BARN/AABARN.xaa.pdbqt.gz
mkdir -pv AA/BARO && wget http://files.docking.org/3D/AA/BARO/AABARO.xaa.pdbqt.gz -O AA/BARO/AABARO.xaa.pdbqt.gz
mkdir -pv AA/BBMM && wget http://files.docking.org/3D/AA/BBMM/AABBMM.xaa.pdbqt.gz -O AA/BBMM/AABBMM.xaa.pdbqt.gz
mkdir -pv AA/BBMN && wget http://files.docking.org/3D/AA/BBMN/AABBMN.xaa.pdbqt.gz -O AA/BBMN/AABBMN.xaa.pdbqt.gz
mkdir -pv AA/BBMO && wget http://files.docking.org/3D/AA/BBMO/AABBMO.xaa.pdbqt.gz -O AA/BBMO/AABBMO.xaa.pdbqt.gz
mkdir -pv AA/BBRM && wget http://files.docking.org/3D/AA/BBRM/AABBRM.xaa.pdbqt.gz -O AA/BBRM/AABBRM.xaa.pdbqt.gz
mkdir -pv AA/BBRN && wget http://files.docking.org/3D/AA/BBRN/AABBRN.xaa.pdbqt.gz -O AA/BBRN/AABBRN.xaa.pdbqt.gz
mkdir -pv AA/BBRO && wget http://files.docking.org/3D/AA/BBRO/AABBRO.xaa.pdbqt.gz -O AA/BBRO/AABBRO.xaa.pdbqt.gz
mkdir -pv AA/BBRP && wget http://files.docking.org/3D/AA/BBRP/AABBRP.xaa.pdbqt.gz -O AA/BBRP/AABBRP.xaa.pdbqt.gz
mkdir -pv AA/BDMM && wget http://files.docking.org/3D/AA/BDMM/AABDMM.xaa.pdbqt.gz -O AA/BDMM/AABDMM.xaa.pdbqt.gz
mkdir -pv AA/BDMN && wget http://files.docking.org/3D/AA/BDMN/AABDMN.xaa.pdbqt.gz -O AA/BDMN/AABDMN.xaa.pdbqt.gz
mkdir -pv AA/BDMO && wget http://files.docking.org/3D/AA/BDMO/AABDMO.xaa.pdbqt.gz -O AA/BDMO/AABDMO.xaa.pdbqt.gz
mkdir -pv AA/BDRM && wget http://files.docking.org/3D/AA/BDRM/AABDRM.xaa.pdbqt.gz -O AA/BDRM/AABDRM.xaa.pdbqt.gz
mkdir -pv AA/BDRN && wget http://files.docking.org/3D/AA/BDRN/AABDRN.xaa.pdbqt.gz -O AA/BDRN/AABDRN.xaa.pdbqt.gz
mkdir -pv AA/BDRO && wget http://files.docking.org/3D/AA/BDRO/AABDRO.xaa.pdbqt.gz -O AA/BDRO/AABDRO.xaa.pdbqt.gz
mkdir -pv AA/CAMM && wget http://files.docking.org/3D/AA/CAMM/AACAMM.xaa.pdbqt.gz -O AA/CAMM/AACAMM.xaa.pdbqt.gz
mkdir -pv AA/CAMN && wget http://files.docking.org/3D/AA/CAMN/AACAMN.xaa.pdbqt.gz -O AA/CAMN/AACAMN.xaa.pdbqt.gz
mkdir -pv AA/CARL && wget http://files.docking.org/3D/AA/CARL/AACARL.xaa.pdbqt.gz -O AA/CARL/AACARL.xaa.pdbqt.gz
mkdir -pv AA/CARM && wget http://files.docking.org/3D/AA/CARM/AACARM.xaa.pdbqt.gz -O AA/CARM/AACARM.xaa.pdbqt.gz
mkdir -pv AA/CARN && wget http://files.docking.org/3D/AA/CARN/AACARN.xaa.pdbqt.gz -O AA/CARN/AACARN.xaa.pdbqt.gz
mkdir -pv AA/CARO && wget http://files.docking.org/3D/AA/CARO/AACARO.xaa.pdbqt.gz -O AA/CARO/AACARO.xaa.pdbqt.gz
mkdir -pv AA/CARP && wget http://files.docking.org/3D/AA/CARP/AACARP.xaa.pdbqt.gz -O AA/CARP/AACARP.xaa.pdbqt.gz
mkdir -pv AA/CBMN && wget http://files.docking.org/3D/AA/CBMN/AACBMN.xaa.pdbqt.gz -O AA/CBMN/AACBMN.xaa.pdbqt.gz
mkdir -pv AA/CBRM && wget http://files.docking.org/3D/AA/CBRM/AACBRM.xaa.pdbqt.gz -O AA/CBRM/AACBRM.xaa.pdbqt.gz
mkdir -pv AA/CBRN && wget http://files.docking.org/3D/AA/CBRN/AACBRN.xaa.pdbqt.gz -O AA/CBRN/AACBRN.xaa.pdbqt.gz
mkdir -pv AA/CBRO && wget http://files.docking.org/3D/AA/CBRO/AACBRO.xaa.pdbqt.gz -O AA/CBRO/AACBRO.xaa.pdbqt.gz
mkdir -pv AA/CDRL && wget http://files.docking.org/3D/AA/CDRL/AACDRL.xaa.pdbqt.gz -O AA/CDRL/AACDRL.xaa.pdbqt.gz
mkdir -pv AA/EAML && wget http://files.docking.org/3D/AA/EAML/AAEAML.xaa.pdbqt.gz -O AA/EAML/AAEAML.xaa.pdbqt.gz
mkdir -pv AA/EAMM && wget http://files.docking.org/3D/AA/EAMM/AAEAMM.xaa.pdbqt.gz -O AA/EAMM/AAEAMM.xaa.pdbqt.gz
mkdir -pv AA/EAMN && wget http://files.docking.org/3D/AA/EAMN/AAEAMN.xaa.pdbqt.gz -O AA/EAMN/AAEAMN.xaa.pdbqt.gz
mkdir -pv AA/EAMO && wget http://files.docking.org/3D/AA/EAMO/AAEAMO.xaa.pdbqt.gz -O AA/EAMO/AAEAMO.xaa.pdbqt.gz
mkdir -pv AA/EAMP && wget http://files.docking.org/3D/AA/EAMP/AAEAMP.xaa.pdbqt.gz -O AA/EAMP/AAEAMP.xaa.pdbqt.gz
mkdir -pv AA/EARL && wget http://files.docking.org/3D/AA/EARL/AAEARL.xaa.pdbqt.gz -O AA/EARL/AAEARL.xaa.pdbqt.gz
mkdir -pv AA/EARM && wget http://files.docking.org/3D/AA/EARM/AAEARM.xaa.pdbqt.gz -O AA/EARM/AAEARM.xaa.pdbqt.gz
mkdir -pv AA/EARN && wget http://files.docking.org/3D/AA/EARN/AAEARN.xaa.pdbqt.gz -O AA/EARN/AAEARN.xaa.pdbqt.gz
mkdir -pv AA/EARO && wget http://files.docking.org/3D/AA/EARO/AAEARO.xaa.pdbqt.gz -O AA/EARO/AAEARO.xaa.pdbqt.gz
mkdir -pv AA/EARP && wget http://files.docking.org/3D/AA/EARP/AAEARP.xaa.pdbqt.gz -O AA/EARP/AAEARP.xaa.pdbqt.gz
mkdir -pv AA/EBMM && wget http://files.docking.org/3D/AA/EBMM/AAEBMM.xaa.pdbqt.gz -O AA/EBMM/AAEBMM.xaa.pdbqt.gz
mkdir -pv AA/EBMN && wget http://files.docking.org/3D/AA/EBMN/AAEBMN.xaa.pdbqt.gz -O AA/EBMN/AAEBMN.xaa.pdbqt.gz
mkdir -pv AA/EBMO && wget http://files.docking.org/3D/AA/EBMO/AAEBMO.xaa.pdbqt.gz -O AA/EBMO/AAEBMO.xaa.pdbqt.gz
mkdir -pv AA/EBRL && wget http://files.docking.org/3D/AA/EBRL/AAEBRL.xaa.pdbqt.gz -O AA/EBRL/AAEBRL.xaa.pdbqt.gz
mkdir -pv AA/EBRM && wget http://files.docking.org/3D/AA/EBRM/AAEBRM.xaa.pdbqt.gz -O AA/EBRM/AAEBRM.xaa.pdbqt.gz
mkdir -pv AA/EBRN && wget http://files.docking.org/3D/AA/EBRN/AAEBRN.xaa.pdbqt.gz -O AA/EBRN/AAEBRN.xaa.pdbqt.gz
mkdir -pv AA/EBRO && wget http://files.docking.org/3D/AA/EBRO/AAEBRO.xaa.pdbqt.gz -O AA/EBRO/AAEBRO.xaa.pdbqt.gz
mkdir -pv AA/EBRP && wget http://files.docking.org/3D/AA/EBRP/AAEBRP.xaa.pdbqt.gz -O AA/EBRP/AAEBRP.xaa.pdbqt.gz
mkdir -pv AA/EDML && wget http://files.docking.org/3D/AA/EDML/AAEDML.xaa.pdbqt.gz -O AA/EDML/AAEDML.xaa.pdbqt.gz
mkdir -pv AA/EDMM && wget http://files.docking.org/3D/AA/EDMM/AAEDMM.xaa.pdbqt.gz -O AA/EDMM/AAEDMM.xaa.pdbqt.gz
mkdir -pv AA/EDMN && wget http://files.docking.org/3D/AA/EDMN/AAEDMN.xaa.pdbqt.gz -O AA/EDMN/AAEDMN.xaa.pdbqt.gz
mkdir -pv AA/EDMO && wget http://files.docking.org/3D/AA/EDMO/AAEDMO.xaa.pdbqt.gz -O AA/EDMO/AAEDMO.xaa.pdbqt.gz
mkdir -pv AA/EDMP && wget http://files.docking.org/3D/AA/EDMP/AAEDMP.xaa.pdbqt.gz -O AA/EDMP/AAEDMP.xaa.pdbqt.gz
mkdir -pv AA/EDRL && wget http://files.docking.org/3D/AA/EDRL/AAEDRL.xaa.pdbqt.gz -O AA/EDRL/AAEDRL.xaa.pdbqt.gz
mkdir -pv AA/EDRM && wget http://files.docking.org/3D/AA/EDRM/AAEDRM.xaa.pdbqt.gz -O AA/EDRM/AAEDRM.xaa.pdbqt.gz
mkdir -pv AA/EDRN && wget http://files.docking.org/3D/AA/EDRN/AAEDRN.xaa.pdbqt.gz -O AA/EDRN/AAEDRN.xaa.pdbqt.gz
mkdir -pv AA/EDRO && wget http://files.docking.org/3D/AA/EDRO/AAEDRO.xaa.pdbqt.gz -O AA/EDRO/AAEDRO.xaa.pdbqt.gz
mkdir -pv AA/EDRP && wget http://files.docking.org/3D/AA/EDRP/AAEDRP.xaa.pdbqt.gz -O AA/EDRP/AAEDRP.xaa.pdbqt.gz
mkdir -pv BA/AAML && wget http://files.docking.org/3D/BA/AAML/BAAAML.xaa.pdbqt.gz -O BA/AAML/BAAAML.xaa.pdbqt.gz
mkdir -pv BA/AAMM && wget http://files.docking.org/3D/BA/AAMM/BAAAMM.xaa.pdbqt.gz -O BA/AAMM/BAAAMM.xaa.pdbqt.gz
mkdir -pv BA/AAMN && wget http://files.docking.org/3D/BA/AAMN/BAAAMN.xaa.pdbqt.gz -O BA/AAMN/BAAAMN.xaa.pdbqt.gz
mkdir -pv BA/AAMO && wget http://files.docking.org/3D/BA/AAMO/BAAAMO.xaa.pdbqt.gz -O BA/AAMO/BAAAMO.xaa.pdbqt.gz
mkdir -pv BA/AAMP && wget http://files.docking.org/3D/BA/AAMP/BAAAMP.xaa.pdbqt.gz -O BA/AAMP/BAAAMP.xaa.pdbqt.gz
mkdir -pv BA/AARL && wget http://files.docking.org/3D/BA/AARL/BAAARL.xaa.pdbqt.gz -O BA/AARL/BAAARL.xaa.pdbqt.gz
mkdir -pv BA/AARM && wget http://files.docking.org/3D/BA/AARM/BAAARM.xaa.pdbqt.gz -O BA/AARM/BAAARM.xaa.pdbqt.gz
mkdir -pv BA/AARN && wget http://files.docking.org/3D/BA/AARN/BAAARN.xaa.pdbqt.gz -O BA/AARN/BAAARN.xaa.pdbqt.gz
mkdir -pv BA/AARO && wget http://files.docking.org/3D/BA/AARO/BAAARO.xaa.pdbqt.gz -O BA/AARO/BAAARO.xaa.pdbqt.gz
mkdir -pv BA/AARP && wget http://files.docking.org/3D/BA/AARP/BAAARP.xaa.pdbqt.gz -O BA/AARP/BAAARP.xaa.pdbqt.gz
mkdir -pv BA/ABML && wget http://files.docking.org/3D/BA/ABML/BAABML.xaa.pdbqt.gz -O BA/ABML/BAABML.xaa.pdbqt.gz
mkdir -pv BA/ABMM && wget http://files.docking.org/3D/BA/ABMM/BAABMM.xaa.pdbqt.gz -O BA/ABMM/BAABMM.xaa.pdbqt.gz
mkdir -pv BA/ABMN && wget http://files.docking.org/3D/BA/ABMN/BAABMN.xaa.pdbqt.gz -O BA/ABMN/BAABMN.xaa.pdbqt.gz
mkdir -pv BA/ABMO && wget http://files.docking.org/3D/BA/ABMO/BAABMO.xaa.pdbqt.gz -O BA/ABMO/BAABMO.xaa.pdbqt.gz
mkdir -pv BA/ABMP && wget http://files.docking.org/3D/BA/ABMP/BAABMP.xaa.pdbqt.gz -O BA/ABMP/BAABMP.xaa.pdbqt.gz
mkdir -pv BA/ABRL && wget http://files.docking.org/3D/BA/ABRL/BAABRL.xaa.pdbqt.gz -O BA/ABRL/BAABRL.xaa.pdbqt.gz
mkdir -pv BA/ABRM && wget http://files.docking.org/3D/BA/ABRM/BAABRM.xaa.pdbqt.gz -O BA/ABRM/BAABRM.xaa.pdbqt.gz
mkdir -pv BA/ABRN && wget http://files.docking.org/3D/BA/ABRN/BAABRN.xaa.pdbqt.gz -O BA/ABRN/BAABRN.xaa.pdbqt.gz
mkdir -pv BA/ABRO && wget http://files.docking.org/3D/BA/ABRO/BAABRO.xaa.pdbqt.gz -O BA/ABRO/BAABRO.xaa.pdbqt.gz
mkdir -pv BA/ABRP && wget http://files.docking.org/3D/BA/ABRP/BAABRP.xaa.pdbqt.gz -O BA/ABRP/BAABRP.xaa.pdbqt.gz
mkdir -pv BA/ADML && wget http://files.docking.org/3D/BA/ADML/BAADML.xaa.pdbqt.gz -O BA/ADML/BAADML.xaa.pdbqt.gz
mkdir -pv BA/ADMM && wget http://files.docking.org/3D/BA/ADMM/BAADMM.xaa.pdbqt.gz -O BA/ADMM/BAADMM.xaa.pdbqt.gz
mkdir -pv BA/ADMN && wget http://files.docking.org/3D/BA/ADMN/BAADMN.xaa.pdbqt.gz -O BA/ADMN/BAADMN.xaa.pdbqt.gz
mkdir -pv BA/ADMO && wget http://files.docking.org/3D/BA/ADMO/BAADMO.xaa.pdbqt.gz -O BA/ADMO/BAADMO.xaa.pdbqt.gz
mkdir -pv BA/ADMP && wget http://files.docking.org/3D/BA/ADMP/BAADMP.xaa.pdbqt.gz -O BA/ADMP/BAADMP.xaa.pdbqt.gz
mkdir -pv BA/ADRL && wget http://files.docking.org/3D/BA/ADRL/BAADRL.xaa.pdbqt.gz -O BA/ADRL/BAADRL.xaa.pdbqt.gz
mkdir -pv BA/ADRM && wget http://files.docking.org/3D/BA/ADRM/BAADRM.xaa.pdbqt.gz -O BA/ADRM/BAADRM.xaa.pdbqt.gz
mkdir -pv BA/ADRN && wget http://files.docking.org/3D/BA/ADRN/BAADRN.xaa.pdbqt.gz -O BA/ADRN/BAADRN.xaa.pdbqt.gz
mkdir -pv BA/ADRO && wget http://files.docking.org/3D/BA/ADRO/BAADRO.xaa.pdbqt.gz -O BA/ADRO/BAADRO.xaa.pdbqt.gz
mkdir -pv BA/ADRP && wget http://files.docking.org/3D/BA/ADRP/BAADRP.xaa.pdbqt.gz -O BA/ADRP/BAADRP.xaa.pdbqt.gz
mkdir -pv BA/BAML && wget http://files.docking.org/3D/BA/BAML/BABAML.xaa.pdbqt.gz -O BA/BAML/BABAML.xaa.pdbqt.gz
mkdir -pv BA/BAMM && wget http://files.docking.org/3D/BA/BAMM/BABAMM.xaa.pdbqt.gz -O BA/BAMM/BABAMM.xaa.pdbqt.gz
mkdir -pv BA/BAMN && wget http://files.docking.org/3D/BA/BAMN/BABAMN.xaa.pdbqt.gz -O BA/BAMN/BABAMN.xaa.pdbqt.gz
mkdir -pv BA/BAMO && wget http://files.docking.org/3D/BA/BAMO/BABAMO.xaa.pdbqt.gz -O BA/BAMO/BABAMO.xaa.pdbqt.gz
mkdir -pv BA/BARL && wget http://files.docking.org/3D/BA/BARL/BABARL.xaa.pdbqt.gz -O BA/BARL/BABARL.xaa.pdbqt.gz
mkdir -pv BA/BARM && wget http://files.docking.org/3D/BA/BARM/BABARM.xaa.pdbqt.gz -O BA/BARM/BABARM.xaa.pdbqt.gz
mkdir -pv BA/BARN && wget http://files.docking.org/3D/BA/BARN/BABARN.xaa.pdbqt.gz -O BA/BARN/BABARN.xaa.pdbqt.gz
mkdir -pv BA/BARO && wget http://files.docking.org/3D/BA/BARO/BABARO.xaa.pdbqt.gz -O BA/BARO/BABARO.xaa.pdbqt.gz
mkdir -pv BA/BARP && wget http://files.docking.org/3D/BA/BARP/BABARP.xaa.pdbqt.gz -O BA/BARP/BABARP.xaa.pdbqt.gz
mkdir -pv BA/BBML && wget http://files.docking.org/3D/BA/BBML/BABBML.xaa.pdbqt.gz -O BA/BBML/BABBML.xaa.pdbqt.gz
mkdir -pv BA/BBMM && wget http://files.docking.org/3D/BA/BBMM/BABBMM.xaa.pdbqt.gz -O BA/BBMM/BABBMM.xaa.pdbqt.gz
mkdir -pv BA/BBRL && wget http://files.docking.org/3D/BA/BBRL/BABBRL.xaa.pdbqt.gz -O BA/BBRL/BABBRL.xaa.pdbqt.gz
mkdir -pv BA/BBRM && wget http://files.docking.org/3D/BA/BBRM/BABBRM.xaa.pdbqt.gz -O BA/BBRM/BABBRM.xaa.pdbqt.gz
mkdir -pv BA/BBRN && wget http://files.docking.org/3D/BA/BBRN/BABBRN.xaa.pdbqt.gz -O BA/BBRN/BABBRN.xaa.pdbqt.gz
mkdir -pv BA/BBRO && wget http://files.docking.org/3D/BA/BBRO/BABBRO.xaa.pdbqt.gz -O BA/BBRO/BABBRO.xaa.pdbqt.gz
mkdir -pv BA/BBRP && wget http://files.docking.org/3D/BA/BBRP/BABBRP.xaa.pdbqt.gz -O BA/BBRP/BABBRP.xaa.pdbqt.gz
mkdir -pv BA/BDMM && wget http://files.docking.org/3D/BA/BDMM/BABDMM.xaa.pdbqt.gz -O BA/BDMM/BABDMM.xaa.pdbqt.gz
mkdir -pv BA/BDMN && wget http://files.docking.org/3D/BA/BDMN/BABDMN.xaa.pdbqt.gz -O BA/BDMN/BABDMN.xaa.pdbqt.gz
mkdir -pv BA/BDMO && wget http://files.docking.org/3D/BA/BDMO/BABDMO.xaa.pdbqt.gz -O BA/BDMO/BABDMO.xaa.pdbqt.gz
mkdir -pv BA/BDRM && wget http://files.docking.org/3D/BA/BDRM/BABDRM.xaa.pdbqt.gz -O BA/BDRM/BABDRM.xaa.pdbqt.gz
mkdir -pv BA/BDRN && wget http://files.docking.org/3D/BA/BDRN/BABDRN.xaa.pdbqt.gz -O BA/BDRN/BABDRN.xaa.pdbqt.gz
mkdir -pv BA/BDRO && wget http://files.docking.org/3D/BA/BDRO/BABDRO.xaa.pdbqt.gz -O BA/BDRO/BABDRO.xaa.pdbqt.gz
mkdir -pv BA/CAMM && wget http://files.docking.org/3D/BA/CAMM/BACAMM.xaa.pdbqt.gz -O BA/CAMM/BACAMM.xaa.pdbqt.gz
mkdir -pv BA/CAMN && wget http://files.docking.org/3D/BA/CAMN/BACAMN.xaa.pdbqt.gz -O BA/CAMN/BACAMN.xaa.pdbqt.gz
mkdir -pv BA/CAMO && wget http://files.docking.org/3D/BA/CAMO/BACAMO.xaa.pdbqt.gz -O BA/CAMO/BACAMO.xaa.pdbqt.gz
mkdir -pv BA/CARL && wget http://files.docking.org/3D/BA/CARL/BACARL.xaa.pdbqt.gz -O BA/CARL/BACARL.xaa.pdbqt.gz
mkdir -pv BA/CARM && wget http://files.docking.org/3D/BA/CARM/BACARM.xaa.pdbqt.gz -O BA/CARM/BACARM.xaa.pdbqt.gz
mkdir -pv BA/CARN && wget http://files.docking.org/3D/BA/CARN/BACARN.xaa.pdbqt.gz -O BA/CARN/BACARN.xaa.pdbqt.gz
mkdir -pv BA/CARO && wget http://files.docking.org/3D/BA/CARO/BACARO.xaa.pdbqt.gz -O BA/CARO/BACARO.xaa.pdbqt.gz
mkdir -pv BA/CBMM && wget http://files.docking.org/3D/BA/CBMM/BACBMM.xaa.pdbqt.gz -O BA/CBMM/BACBMM.xaa.pdbqt.gz
mkdir -pv BA/CBMN && wget http://files.docking.org/3D/BA/CBMN/BACBMN.xaa.pdbqt.gz -O BA/CBMN/BACBMN.xaa.pdbqt.gz
mkdir -pv BA/CBRL && wget http://files.docking.org/3D/BA/CBRL/BACBRL.xaa.pdbqt.gz -O BA/CBRL/BACBRL.xaa.pdbqt.gz
mkdir -pv BA/CBRM && wget http://files.docking.org/3D/BA/CBRM/BACBRM.xaa.pdbqt.gz -O BA/CBRM/BACBRM.xaa.pdbqt.gz
mkdir -pv BA/CBRN && wget http://files.docking.org/3D/BA/CBRN/BACBRN.xaa.pdbqt.gz -O BA/CBRN/BACBRN.xaa.pdbqt.gz
mkdir -pv BA/CBRO && wget http://files.docking.org/3D/BA/CBRO/BACBRO.xaa.pdbqt.gz -O BA/CBRO/BACBRO.xaa.pdbqt.gz
mkdir -pv BA/CDRN && wget http://files.docking.org/3D/BA/CDRN/BACDRN.xaa.pdbqt.gz -O BA/CDRN/BACDRN.xaa.pdbqt.gz
mkdir -pv BA/EAMM && wget http://files.docking.org/3D/BA/EAMM/BAEAMM.xaa.pdbqt.gz -O BA/EAMM/BAEAMM.xaa.pdbqt.gz
mkdir -pv BA/EAMN && wget http://files.docking.org/3D/BA/EAMN/BAEAMN.xaa.pdbqt.gz -O BA/EAMN/BAEAMN.xaa.pdbqt.gz
mkdir -pv BA/EAMO && wget http://files.docking.org/3D/BA/EAMO/BAEAMO.xaa.pdbqt.gz -O BA/EAMO/BAEAMO.xaa.pdbqt.gz
mkdir -pv BA/EARL && wget http://files.docking.org/3D/BA/EARL/BAEARL.xaa.pdbqt.gz -O BA/EARL/BAEARL.xaa.pdbqt.gz
mkdir -pv BA/EARM && wget http://files.docking.org/3D/BA/EARM/BAEARM.xaa.pdbqt.gz -O BA/EARM/BAEARM.xaa.pdbqt.gz
mkdir -pv BA/EARN && wget http://files.docking.org/3D/BA/EARN/BAEARN.xaa.pdbqt.gz -O BA/EARN/BAEARN.xaa.pdbqt.gz
mkdir -pv BA/EARO && wget http://files.docking.org/3D/BA/EARO/BAEARO.xaa.pdbqt.gz -O BA/EARO/BAEARO.xaa.pdbqt.gz
mkdir -pv BA/EARP && wget http://files.docking.org/3D/BA/EARP/BAEARP.xaa.pdbqt.gz -O BA/EARP/BAEARP.xaa.pdbqt.gz
mkdir -pv BA/EBML && wget http://files.docking.org/3D/BA/EBML/BAEBML.xaa.pdbqt.gz -O BA/EBML/BAEBML.xaa.pdbqt.gz
mkdir -pv BA/EBMM && wget http://files.docking.org/3D/BA/EBMM/BAEBMM.xaa.pdbqt.gz -O BA/EBMM/BAEBMM.xaa.pdbqt.gz
mkdir -pv BA/EBMN && wget http://files.docking.org/3D/BA/EBMN/BAEBMN.xaa.pdbqt.gz -O BA/EBMN/BAEBMN.xaa.pdbqt.gz
mkdir -pv BA/EBMO && wget http://files.docking.org/3D/BA/EBMO/BAEBMO.xaa.pdbqt.gz -O BA/EBMO/BAEBMO.xaa.pdbqt.gz
mkdir -pv BA/EBMP && wget http://files.docking.org/3D/BA/EBMP/BAEBMP.xaa.pdbqt.gz -O BA/EBMP/BAEBMP.xaa.pdbqt.gz
mkdir -pv BA/EBRL && wget http://files.docking.org/3D/BA/EBRL/BAEBRL.xaa.pdbqt.gz -O BA/EBRL/BAEBRL.xaa.pdbqt.gz
mkdir -pv BA/EBRM && wget http://files.docking.org/3D/BA/EBRM/BAEBRM.xaa.pdbqt.gz -O BA/EBRM/BAEBRM.xaa.pdbqt.gz
mkdir -pv BA/EBRN && wget http://files.docking.org/3D/BA/EBRN/BAEBRN.xaa.pdbqt.gz -O BA/EBRN/BAEBRN.xaa.pdbqt.gz
mkdir -pv BA/EBRO && wget http://files.docking.org/3D/BA/EBRO/BAEBRO.xaa.pdbqt.gz -O BA/EBRO/BAEBRO.xaa.pdbqt.gz
mkdir -pv BA/EBRP && wget http://files.docking.org/3D/BA/EBRP/BAEBRP.xaa.pdbqt.gz -O BA/EBRP/BAEBRP.xaa.pdbqt.gz
mkdir -pv BA/EDML && wget http://files.docking.org/3D/BA/EDML/BAEDML.xaa.pdbqt.gz -O BA/EDML/BAEDML.xaa.pdbqt.gz
mkdir -pv BA/EDMM && wget http://files.docking.org/3D/BA/EDMM/BAEDMM.xaa.pdbqt.gz -O BA/EDMM/BAEDMM.xaa.pdbqt.gz
mkdir -pv BA/EDMN && wget http://files.docking.org/3D/BA/EDMN/BAEDMN.xaa.pdbqt.gz -O BA/EDMN/BAEDMN.xaa.pdbqt.gz
mkdir -pv BA/EDMO && wget http://files.docking.org/3D/BA/EDMO/BAEDMO.xaa.pdbqt.gz -O BA/EDMO/BAEDMO.xaa.pdbqt.gz
mkdir -pv BA/EDMP && wget http://files.docking.org/3D/BA/EDMP/BAEDMP.xaa.pdbqt.gz -O BA/EDMP/BAEDMP.xaa.pdbqt.gz
mkdir -pv BA/EDRL && wget http://files.docking.org/3D/BA/EDRL/BAEDRL.xaa.pdbqt.gz -O BA/EDRL/BAEDRL.xaa.pdbqt.gz
mkdir -pv BA/EDRM && wget http://files.docking.org/3D/BA/EDRM/BAEDRM.xaa.pdbqt.gz -O BA/EDRM/BAEDRM.xaa.pdbqt.gz
mkdir -pv BA/EDRN && wget http://files.docking.org/3D/BA/EDRN/BAEDRN.xaa.pdbqt.gz -O BA/EDRN/BAEDRN.xaa.pdbqt.gz
mkdir -pv BA/EDRO && wget http://files.docking.org/3D/BA/EDRO/BAEDRO.xaa.pdbqt.gz -O BA/EDRO/BAEDRO.xaa.pdbqt.gz
mkdir -pv BA/EDRP && wget http://files.docking.org/3D/BA/EDRP/BAEDRP.xaa.pdbqt.gz -O BA/EDRP/BAEDRP.xaa.pdbqt.gz
