mkdir -pv EC/AAML && wget http://files.docking.org/3D/EC/AAML/ECAAML.xaa.pdbqt.gz -O EC/AAML/ECAAML.xaa.pdbqt.gz
mkdir -pv EC/AAMM && wget http://files.docking.org/3D/EC/AAMM/ECAAMM.xaa.pdbqt.gz -O EC/AAMM/ECAAMM.xaa.pdbqt.gz
mkdir -pv EC/AAMN && wget http://files.docking.org/3D/EC/AAMN/ECAAMN.xaa.pdbqt.gz -O EC/AAMN/ECAAMN.xaa.pdbqt.gz
mkdir -pv EC/AAMO && wget http://files.docking.org/3D/EC/AAMO/ECAAMO.xaa.pdbqt.gz -O EC/AAMO/ECAAMO.xaa.pdbqt.gz
mkdir -pv EC/AAMP && wget http://files.docking.org/3D/EC/AAMP/ECAAMP.xaa.pdbqt.gz -O EC/AAMP/ECAAMP.xaa.pdbqt.gz
mkdir -pv EC/AARL && wget http://files.docking.org/3D/EC/AARL/ECAARL.xaa.pdbqt.gz -O EC/AARL/ECAARL.xaa.pdbqt.gz
mkdir -pv EC/AARM && wget http://files.docking.org/3D/EC/AARM/ECAARM.xaa.pdbqt.gz -O EC/AARM/ECAARM.xaa.pdbqt.gz
mkdir -pv EC/AARN && wget http://files.docking.org/3D/EC/AARN/ECAARN.xaa.pdbqt.gz -O EC/AARN/ECAARN.xaa.pdbqt.gz
mkdir -pv EC/AARO && wget http://files.docking.org/3D/EC/AARO/ECAARO.xaa.pdbqt.gz -O EC/AARO/ECAARO.xaa.pdbqt.gz
mkdir -pv EC/AARP && wget http://files.docking.org/3D/EC/AARP/ECAARP.xaa.pdbqt.gz -O EC/AARP/ECAARP.xaa.pdbqt.gz
mkdir -pv EC/ABML && wget http://files.docking.org/3D/EC/ABML/ECABML.xaa.pdbqt.gz -O EC/ABML/ECABML.xaa.pdbqt.gz
mkdir -pv EC/ABMM && wget http://files.docking.org/3D/EC/ABMM/ECABMM.xaa.pdbqt.gz -O EC/ABMM/ECABMM.xaa.pdbqt.gz
mkdir -pv EC/ABMN && wget http://files.docking.org/3D/EC/ABMN/ECABMN.xaa.pdbqt.gz -O EC/ABMN/ECABMN.xaa.pdbqt.gz
mkdir -pv EC/ABMO && wget http://files.docking.org/3D/EC/ABMO/ECABMO.xaa.pdbqt.gz -O EC/ABMO/ECABMO.xaa.pdbqt.gz
mkdir -pv EC/ABMP && wget http://files.docking.org/3D/EC/ABMP/ECABMP.xaa.pdbqt.gz -O EC/ABMP/ECABMP.xaa.pdbqt.gz
mkdir -pv EC/ABRL && wget http://files.docking.org/3D/EC/ABRL/ECABRL.xaa.pdbqt.gz -O EC/ABRL/ECABRL.xaa.pdbqt.gz
mkdir -pv EC/ABRM && wget http://files.docking.org/3D/EC/ABRM/ECABRM.xaa.pdbqt.gz -O EC/ABRM/ECABRM.xaa.pdbqt.gz
mkdir -pv EC/ABRN && wget http://files.docking.org/3D/EC/ABRN/ECABRN.xaa.pdbqt.gz -O EC/ABRN/ECABRN.xaa.pdbqt.gz
mkdir -pv EC/ABRO && wget http://files.docking.org/3D/EC/ABRO/ECABRO.xaa.pdbqt.gz -O EC/ABRO/ECABRO.xaa.pdbqt.gz
mkdir -pv EC/ABRP && wget http://files.docking.org/3D/EC/ABRP/ECABRP.xaa.pdbqt.gz -O EC/ABRP/ECABRP.xaa.pdbqt.gz
mkdir -pv EC/ADML && wget http://files.docking.org/3D/EC/ADML/ECADML.xaa.pdbqt.gz -O EC/ADML/ECADML.xaa.pdbqt.gz
mkdir -pv EC/ADMM && wget http://files.docking.org/3D/EC/ADMM/ECADMM.xaa.pdbqt.gz -O EC/ADMM/ECADMM.xaa.pdbqt.gz
mkdir -pv EC/ADMM && wget http://files.docking.org/3D/EC/ADMM/ECADMM.xab.pdbqt.gz -O EC/ADMM/ECADMM.xab.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xaa.pdbqt.gz -O EC/ADMN/ECADMN.xaa.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xab.pdbqt.gz -O EC/ADMN/ECADMN.xab.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xac.pdbqt.gz -O EC/ADMN/ECADMN.xac.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xad.pdbqt.gz -O EC/ADMN/ECADMN.xad.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xae.pdbqt.gz -O EC/ADMN/ECADMN.xae.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xaf.pdbqt.gz -O EC/ADMN/ECADMN.xaf.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xag.pdbqt.gz -O EC/ADMN/ECADMN.xag.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xah.pdbqt.gz -O EC/ADMN/ECADMN.xah.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xai.pdbqt.gz -O EC/ADMN/ECADMN.xai.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xaj.pdbqt.gz -O EC/ADMN/ECADMN.xaj.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xak.pdbqt.gz -O EC/ADMN/ECADMN.xak.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xal.pdbqt.gz -O EC/ADMN/ECADMN.xal.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xam.pdbqt.gz -O EC/ADMN/ECADMN.xam.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xan.pdbqt.gz -O EC/ADMN/ECADMN.xan.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xao.pdbqt.gz -O EC/ADMN/ECADMN.xao.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xap.pdbqt.gz -O EC/ADMN/ECADMN.xap.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xaq.pdbqt.gz -O EC/ADMN/ECADMN.xaq.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xar.pdbqt.gz -O EC/ADMN/ECADMN.xar.pdbqt.gz
mkdir -pv EC/ADMN && wget http://files.docking.org/3D/EC/ADMN/ECADMN.xas.pdbqt.gz -O EC/ADMN/ECADMN.xas.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xaa.pdbqt.gz -O EC/ADMO/ECADMO.xaa.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xab.pdbqt.gz -O EC/ADMO/ECADMO.xab.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xac.pdbqt.gz -O EC/ADMO/ECADMO.xac.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xad.pdbqt.gz -O EC/ADMO/ECADMO.xad.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xae.pdbqt.gz -O EC/ADMO/ECADMO.xae.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xaf.pdbqt.gz -O EC/ADMO/ECADMO.xaf.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xag.pdbqt.gz -O EC/ADMO/ECADMO.xag.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xah.pdbqt.gz -O EC/ADMO/ECADMO.xah.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xai.pdbqt.gz -O EC/ADMO/ECADMO.xai.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xaj.pdbqt.gz -O EC/ADMO/ECADMO.xaj.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xak.pdbqt.gz -O EC/ADMO/ECADMO.xak.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xal.pdbqt.gz -O EC/ADMO/ECADMO.xal.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xam.pdbqt.gz -O EC/ADMO/ECADMO.xam.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xan.pdbqt.gz -O EC/ADMO/ECADMO.xan.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xao.pdbqt.gz -O EC/ADMO/ECADMO.xao.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xap.pdbqt.gz -O EC/ADMO/ECADMO.xap.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xaq.pdbqt.gz -O EC/ADMO/ECADMO.xaq.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xar.pdbqt.gz -O EC/ADMO/ECADMO.xar.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xas.pdbqt.gz -O EC/ADMO/ECADMO.xas.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xat.pdbqt.gz -O EC/ADMO/ECADMO.xat.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xau.pdbqt.gz -O EC/ADMO/ECADMO.xau.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xav.pdbqt.gz -O EC/ADMO/ECADMO.xav.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xaw.pdbqt.gz -O EC/ADMO/ECADMO.xaw.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xax.pdbqt.gz -O EC/ADMO/ECADMO.xax.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xay.pdbqt.gz -O EC/ADMO/ECADMO.xay.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xaz.pdbqt.gz -O EC/ADMO/ECADMO.xaz.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xba.pdbqt.gz -O EC/ADMO/ECADMO.xba.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xbb.pdbqt.gz -O EC/ADMO/ECADMO.xbb.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xbc.pdbqt.gz -O EC/ADMO/ECADMO.xbc.pdbqt.gz
mkdir -pv EC/ADMO && wget http://files.docking.org/3D/EC/ADMO/ECADMO.xbd.pdbqt.gz -O EC/ADMO/ECADMO.xbd.pdbqt.gz
mkdir -pv EC/ADMP && wget http://files.docking.org/3D/EC/ADMP/ECADMP.xaa.pdbqt.gz -O EC/ADMP/ECADMP.xaa.pdbqt.gz
mkdir -pv EC/ADMP && wget http://files.docking.org/3D/EC/ADMP/ECADMP.xab.pdbqt.gz -O EC/ADMP/ECADMP.xab.pdbqt.gz
mkdir -pv EC/ADMP && wget http://files.docking.org/3D/EC/ADMP/ECADMP.xac.pdbqt.gz -O EC/ADMP/ECADMP.xac.pdbqt.gz
mkdir -pv EC/ADRL && wget http://files.docking.org/3D/EC/ADRL/ECADRL.xaa.pdbqt.gz -O EC/ADRL/ECADRL.xaa.pdbqt.gz
mkdir -pv EC/ADRM && wget http://files.docking.org/3D/EC/ADRM/ECADRM.xaa.pdbqt.gz -O EC/ADRM/ECADRM.xaa.pdbqt.gz
mkdir -pv EC/ADRM && wget http://files.docking.org/3D/EC/ADRM/ECADRM.xab.pdbqt.gz -O EC/ADRM/ECADRM.xab.pdbqt.gz
mkdir -pv EC/ADRM && wget http://files.docking.org/3D/EC/ADRM/ECADRM.xac.pdbqt.gz -O EC/ADRM/ECADRM.xac.pdbqt.gz
mkdir -pv EC/ADRM && wget http://files.docking.org/3D/EC/ADRM/ECADRM.xad.pdbqt.gz -O EC/ADRM/ECADRM.xad.pdbqt.gz
mkdir -pv EC/ADRM && wget http://files.docking.org/3D/EC/ADRM/ECADRM.xae.pdbqt.gz -O EC/ADRM/ECADRM.xae.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xaa.pdbqt.gz -O EC/ADRN/ECADRN.xaa.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xab.pdbqt.gz -O EC/ADRN/ECADRN.xab.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xac.pdbqt.gz -O EC/ADRN/ECADRN.xac.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xad.pdbqt.gz -O EC/ADRN/ECADRN.xad.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xae.pdbqt.gz -O EC/ADRN/ECADRN.xae.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xaf.pdbqt.gz -O EC/ADRN/ECADRN.xaf.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xag.pdbqt.gz -O EC/ADRN/ECADRN.xag.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xah.pdbqt.gz -O EC/ADRN/ECADRN.xah.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xai.pdbqt.gz -O EC/ADRN/ECADRN.xai.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xaj.pdbqt.gz -O EC/ADRN/ECADRN.xaj.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xak.pdbqt.gz -O EC/ADRN/ECADRN.xak.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xal.pdbqt.gz -O EC/ADRN/ECADRN.xal.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xam.pdbqt.gz -O EC/ADRN/ECADRN.xam.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xan.pdbqt.gz -O EC/ADRN/ECADRN.xan.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xao.pdbqt.gz -O EC/ADRN/ECADRN.xao.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xap.pdbqt.gz -O EC/ADRN/ECADRN.xap.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xaq.pdbqt.gz -O EC/ADRN/ECADRN.xaq.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xar.pdbqt.gz -O EC/ADRN/ECADRN.xar.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xas.pdbqt.gz -O EC/ADRN/ECADRN.xas.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xat.pdbqt.gz -O EC/ADRN/ECADRN.xat.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xau.pdbqt.gz -O EC/ADRN/ECADRN.xau.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xav.pdbqt.gz -O EC/ADRN/ECADRN.xav.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xaw.pdbqt.gz -O EC/ADRN/ECADRN.xaw.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xax.pdbqt.gz -O EC/ADRN/ECADRN.xax.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xay.pdbqt.gz -O EC/ADRN/ECADRN.xay.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xaz.pdbqt.gz -O EC/ADRN/ECADRN.xaz.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xba.pdbqt.gz -O EC/ADRN/ECADRN.xba.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbb.pdbqt.gz -O EC/ADRN/ECADRN.xbb.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbc.pdbqt.gz -O EC/ADRN/ECADRN.xbc.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbd.pdbqt.gz -O EC/ADRN/ECADRN.xbd.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbe.pdbqt.gz -O EC/ADRN/ECADRN.xbe.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbf.pdbqt.gz -O EC/ADRN/ECADRN.xbf.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbg.pdbqt.gz -O EC/ADRN/ECADRN.xbg.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbh.pdbqt.gz -O EC/ADRN/ECADRN.xbh.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbi.pdbqt.gz -O EC/ADRN/ECADRN.xbi.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbj.pdbqt.gz -O EC/ADRN/ECADRN.xbj.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbk.pdbqt.gz -O EC/ADRN/ECADRN.xbk.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbl.pdbqt.gz -O EC/ADRN/ECADRN.xbl.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbm.pdbqt.gz -O EC/ADRN/ECADRN.xbm.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbn.pdbqt.gz -O EC/ADRN/ECADRN.xbn.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbo.pdbqt.gz -O EC/ADRN/ECADRN.xbo.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbp.pdbqt.gz -O EC/ADRN/ECADRN.xbp.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbq.pdbqt.gz -O EC/ADRN/ECADRN.xbq.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbr.pdbqt.gz -O EC/ADRN/ECADRN.xbr.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbs.pdbqt.gz -O EC/ADRN/ECADRN.xbs.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbt.pdbqt.gz -O EC/ADRN/ECADRN.xbt.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbu.pdbqt.gz -O EC/ADRN/ECADRN.xbu.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbv.pdbqt.gz -O EC/ADRN/ECADRN.xbv.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbw.pdbqt.gz -O EC/ADRN/ECADRN.xbw.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbx.pdbqt.gz -O EC/ADRN/ECADRN.xbx.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xby.pdbqt.gz -O EC/ADRN/ECADRN.xby.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xbz.pdbqt.gz -O EC/ADRN/ECADRN.xbz.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xca.pdbqt.gz -O EC/ADRN/ECADRN.xca.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcb.pdbqt.gz -O EC/ADRN/ECADRN.xcb.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcc.pdbqt.gz -O EC/ADRN/ECADRN.xcc.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcd.pdbqt.gz -O EC/ADRN/ECADRN.xcd.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xce.pdbqt.gz -O EC/ADRN/ECADRN.xce.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcf.pdbqt.gz -O EC/ADRN/ECADRN.xcf.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcg.pdbqt.gz -O EC/ADRN/ECADRN.xcg.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xch.pdbqt.gz -O EC/ADRN/ECADRN.xch.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xci.pdbqt.gz -O EC/ADRN/ECADRN.xci.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcj.pdbqt.gz -O EC/ADRN/ECADRN.xcj.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xck.pdbqt.gz -O EC/ADRN/ECADRN.xck.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcl.pdbqt.gz -O EC/ADRN/ECADRN.xcl.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcm.pdbqt.gz -O EC/ADRN/ECADRN.xcm.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcn.pdbqt.gz -O EC/ADRN/ECADRN.xcn.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xco.pdbqt.gz -O EC/ADRN/ECADRN.xco.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcp.pdbqt.gz -O EC/ADRN/ECADRN.xcp.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcq.pdbqt.gz -O EC/ADRN/ECADRN.xcq.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcr.pdbqt.gz -O EC/ADRN/ECADRN.xcr.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcs.pdbqt.gz -O EC/ADRN/ECADRN.xcs.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xct.pdbqt.gz -O EC/ADRN/ECADRN.xct.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcu.pdbqt.gz -O EC/ADRN/ECADRN.xcu.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcv.pdbqt.gz -O EC/ADRN/ECADRN.xcv.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcw.pdbqt.gz -O EC/ADRN/ECADRN.xcw.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcx.pdbqt.gz -O EC/ADRN/ECADRN.xcx.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcy.pdbqt.gz -O EC/ADRN/ECADRN.xcy.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xcz.pdbqt.gz -O EC/ADRN/ECADRN.xcz.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xda.pdbqt.gz -O EC/ADRN/ECADRN.xda.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdb.pdbqt.gz -O EC/ADRN/ECADRN.xdb.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdc.pdbqt.gz -O EC/ADRN/ECADRN.xdc.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdd.pdbqt.gz -O EC/ADRN/ECADRN.xdd.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xde.pdbqt.gz -O EC/ADRN/ECADRN.xde.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdf.pdbqt.gz -O EC/ADRN/ECADRN.xdf.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdg.pdbqt.gz -O EC/ADRN/ECADRN.xdg.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdh.pdbqt.gz -O EC/ADRN/ECADRN.xdh.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdi.pdbqt.gz -O EC/ADRN/ECADRN.xdi.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdj.pdbqt.gz -O EC/ADRN/ECADRN.xdj.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdk.pdbqt.gz -O EC/ADRN/ECADRN.xdk.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdl.pdbqt.gz -O EC/ADRN/ECADRN.xdl.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdm.pdbqt.gz -O EC/ADRN/ECADRN.xdm.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdn.pdbqt.gz -O EC/ADRN/ECADRN.xdn.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdo.pdbqt.gz -O EC/ADRN/ECADRN.xdo.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdp.pdbqt.gz -O EC/ADRN/ECADRN.xdp.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdq.pdbqt.gz -O EC/ADRN/ECADRN.xdq.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdr.pdbqt.gz -O EC/ADRN/ECADRN.xdr.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xds.pdbqt.gz -O EC/ADRN/ECADRN.xds.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdt.pdbqt.gz -O EC/ADRN/ECADRN.xdt.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdu.pdbqt.gz -O EC/ADRN/ECADRN.xdu.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdv.pdbqt.gz -O EC/ADRN/ECADRN.xdv.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdw.pdbqt.gz -O EC/ADRN/ECADRN.xdw.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdx.pdbqt.gz -O EC/ADRN/ECADRN.xdx.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdy.pdbqt.gz -O EC/ADRN/ECADRN.xdy.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xdz.pdbqt.gz -O EC/ADRN/ECADRN.xdz.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xea.pdbqt.gz -O EC/ADRN/ECADRN.xea.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xeb.pdbqt.gz -O EC/ADRN/ECADRN.xeb.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xec.pdbqt.gz -O EC/ADRN/ECADRN.xec.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xed.pdbqt.gz -O EC/ADRN/ECADRN.xed.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xee.pdbqt.gz -O EC/ADRN/ECADRN.xee.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xef.pdbqt.gz -O EC/ADRN/ECADRN.xef.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xeg.pdbqt.gz -O EC/ADRN/ECADRN.xeg.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xeh.pdbqt.gz -O EC/ADRN/ECADRN.xeh.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xei.pdbqt.gz -O EC/ADRN/ECADRN.xei.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xej.pdbqt.gz -O EC/ADRN/ECADRN.xej.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xek.pdbqt.gz -O EC/ADRN/ECADRN.xek.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xel.pdbqt.gz -O EC/ADRN/ECADRN.xel.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xem.pdbqt.gz -O EC/ADRN/ECADRN.xem.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xen.pdbqt.gz -O EC/ADRN/ECADRN.xen.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xeo.pdbqt.gz -O EC/ADRN/ECADRN.xeo.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xep.pdbqt.gz -O EC/ADRN/ECADRN.xep.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xeq.pdbqt.gz -O EC/ADRN/ECADRN.xeq.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xer.pdbqt.gz -O EC/ADRN/ECADRN.xer.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xes.pdbqt.gz -O EC/ADRN/ECADRN.xes.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xet.pdbqt.gz -O EC/ADRN/ECADRN.xet.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xeu.pdbqt.gz -O EC/ADRN/ECADRN.xeu.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xev.pdbqt.gz -O EC/ADRN/ECADRN.xev.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xew.pdbqt.gz -O EC/ADRN/ECADRN.xew.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xex.pdbqt.gz -O EC/ADRN/ECADRN.xex.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xey.pdbqt.gz -O EC/ADRN/ECADRN.xey.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xez.pdbqt.gz -O EC/ADRN/ECADRN.xez.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xfa.pdbqt.gz -O EC/ADRN/ECADRN.xfa.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xfb.pdbqt.gz -O EC/ADRN/ECADRN.xfb.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xfc.pdbqt.gz -O EC/ADRN/ECADRN.xfc.pdbqt.gz
mkdir -pv EC/ADRN && wget http://files.docking.org/3D/EC/ADRN/ECADRN.xfd.pdbqt.gz -O EC/ADRN/ECADRN.xfd.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xaa.pdbqt.gz -O EC/ADRO/ECADRO.xaa.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xab.pdbqt.gz -O EC/ADRO/ECADRO.xab.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xac.pdbqt.gz -O EC/ADRO/ECADRO.xac.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xad.pdbqt.gz -O EC/ADRO/ECADRO.xad.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xae.pdbqt.gz -O EC/ADRO/ECADRO.xae.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xaf.pdbqt.gz -O EC/ADRO/ECADRO.xaf.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xag.pdbqt.gz -O EC/ADRO/ECADRO.xag.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xah.pdbqt.gz -O EC/ADRO/ECADRO.xah.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xai.pdbqt.gz -O EC/ADRO/ECADRO.xai.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xaj.pdbqt.gz -O EC/ADRO/ECADRO.xaj.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xak.pdbqt.gz -O EC/ADRO/ECADRO.xak.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xal.pdbqt.gz -O EC/ADRO/ECADRO.xal.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xam.pdbqt.gz -O EC/ADRO/ECADRO.xam.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xan.pdbqt.gz -O EC/ADRO/ECADRO.xan.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xao.pdbqt.gz -O EC/ADRO/ECADRO.xao.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xap.pdbqt.gz -O EC/ADRO/ECADRO.xap.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xaq.pdbqt.gz -O EC/ADRO/ECADRO.xaq.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xar.pdbqt.gz -O EC/ADRO/ECADRO.xar.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xas.pdbqt.gz -O EC/ADRO/ECADRO.xas.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xat.pdbqt.gz -O EC/ADRO/ECADRO.xat.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xau.pdbqt.gz -O EC/ADRO/ECADRO.xau.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xav.pdbqt.gz -O EC/ADRO/ECADRO.xav.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xaw.pdbqt.gz -O EC/ADRO/ECADRO.xaw.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xax.pdbqt.gz -O EC/ADRO/ECADRO.xax.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xay.pdbqt.gz -O EC/ADRO/ECADRO.xay.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xaz.pdbqt.gz -O EC/ADRO/ECADRO.xaz.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xba.pdbqt.gz -O EC/ADRO/ECADRO.xba.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbb.pdbqt.gz -O EC/ADRO/ECADRO.xbb.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbc.pdbqt.gz -O EC/ADRO/ECADRO.xbc.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbd.pdbqt.gz -O EC/ADRO/ECADRO.xbd.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbe.pdbqt.gz -O EC/ADRO/ECADRO.xbe.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbf.pdbqt.gz -O EC/ADRO/ECADRO.xbf.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbg.pdbqt.gz -O EC/ADRO/ECADRO.xbg.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbh.pdbqt.gz -O EC/ADRO/ECADRO.xbh.pdbqt.gz
mkdir -pv EC/ADRO && wget http://files.docking.org/3D/EC/ADRO/ECADRO.xbi.pdbqt.gz -O EC/ADRO/ECADRO.xbi.pdbqt.gz
mkdir -pv EC/ADRP && wget http://files.docking.org/3D/EC/ADRP/ECADRP.xaa.pdbqt.gz -O EC/ADRP/ECADRP.xaa.pdbqt.gz
mkdir -pv EC/ADRP && wget http://files.docking.org/3D/EC/ADRP/ECADRP.xab.pdbqt.gz -O EC/ADRP/ECADRP.xab.pdbqt.gz
mkdir -pv EC/BAML && wget http://files.docking.org/3D/EC/BAML/ECBAML.xaa.pdbqt.gz -O EC/BAML/ECBAML.xaa.pdbqt.gz
mkdir -pv EC/BAMM && wget http://files.docking.org/3D/EC/BAMM/ECBAMM.xaa.pdbqt.gz -O EC/BAMM/ECBAMM.xaa.pdbqt.gz
mkdir -pv EC/BAMN && wget http://files.docking.org/3D/EC/BAMN/ECBAMN.xaa.pdbqt.gz -O EC/BAMN/ECBAMN.xaa.pdbqt.gz
mkdir -pv EC/BAMO && wget http://files.docking.org/3D/EC/BAMO/ECBAMO.xaa.pdbqt.gz -O EC/BAMO/ECBAMO.xaa.pdbqt.gz
mkdir -pv EC/BAMP && wget http://files.docking.org/3D/EC/BAMP/ECBAMP.xaa.pdbqt.gz -O EC/BAMP/ECBAMP.xaa.pdbqt.gz
mkdir -pv EC/BARL && wget http://files.docking.org/3D/EC/BARL/ECBARL.xaa.pdbqt.gz -O EC/BARL/ECBARL.xaa.pdbqt.gz
mkdir -pv EC/BARM && wget http://files.docking.org/3D/EC/BARM/ECBARM.xaa.pdbqt.gz -O EC/BARM/ECBARM.xaa.pdbqt.gz
mkdir -pv EC/BARN && wget http://files.docking.org/3D/EC/BARN/ECBARN.xaa.pdbqt.gz -O EC/BARN/ECBARN.xaa.pdbqt.gz
mkdir -pv EC/BARO && wget http://files.docking.org/3D/EC/BARO/ECBARO.xaa.pdbqt.gz -O EC/BARO/ECBARO.xaa.pdbqt.gz
mkdir -pv EC/BBML && wget http://files.docking.org/3D/EC/BBML/ECBBML.xaa.pdbqt.gz -O EC/BBML/ECBBML.xaa.pdbqt.gz
mkdir -pv EC/BBMM && wget http://files.docking.org/3D/EC/BBMM/ECBBMM.xaa.pdbqt.gz -O EC/BBMM/ECBBMM.xaa.pdbqt.gz
mkdir -pv EC/BBMN && wget http://files.docking.org/3D/EC/BBMN/ECBBMN.xaa.pdbqt.gz -O EC/BBMN/ECBBMN.xaa.pdbqt.gz
mkdir -pv EC/BBMO && wget http://files.docking.org/3D/EC/BBMO/ECBBMO.xaa.pdbqt.gz -O EC/BBMO/ECBBMO.xaa.pdbqt.gz
mkdir -pv EC/BBRL && wget http://files.docking.org/3D/EC/BBRL/ECBBRL.xaa.pdbqt.gz -O EC/BBRL/ECBBRL.xaa.pdbqt.gz
mkdir -pv EC/BBRM && wget http://files.docking.org/3D/EC/BBRM/ECBBRM.xaa.pdbqt.gz -O EC/BBRM/ECBBRM.xaa.pdbqt.gz
mkdir -pv EC/BBRN && wget http://files.docking.org/3D/EC/BBRN/ECBBRN.xaa.pdbqt.gz -O EC/BBRN/ECBBRN.xaa.pdbqt.gz
mkdir -pv EC/BBRO && wget http://files.docking.org/3D/EC/BBRO/ECBBRO.xaa.pdbqt.gz -O EC/BBRO/ECBBRO.xaa.pdbqt.gz
mkdir -pv EC/BBRP && wget http://files.docking.org/3D/EC/BBRP/ECBBRP.xaa.pdbqt.gz -O EC/BBRP/ECBBRP.xaa.pdbqt.gz
mkdir -pv EC/BDML && wget http://files.docking.org/3D/EC/BDML/ECBDML.xaa.pdbqt.gz -O EC/BDML/ECBDML.xaa.pdbqt.gz
mkdir -pv EC/BDMM && wget http://files.docking.org/3D/EC/BDMM/ECBDMM.xaa.pdbqt.gz -O EC/BDMM/ECBDMM.xaa.pdbqt.gz
mkdir -pv EC/BDMN && wget http://files.docking.org/3D/EC/BDMN/ECBDMN.xaa.pdbqt.gz -O EC/BDMN/ECBDMN.xaa.pdbqt.gz
mkdir -pv EC/BDMO && wget http://files.docking.org/3D/EC/BDMO/ECBDMO.xaa.pdbqt.gz -O EC/BDMO/ECBDMO.xaa.pdbqt.gz
mkdir -pv EC/BDMP && wget http://files.docking.org/3D/EC/BDMP/ECBDMP.xaa.pdbqt.gz -O EC/BDMP/ECBDMP.xaa.pdbqt.gz
mkdir -pv EC/BDRL && wget http://files.docking.org/3D/EC/BDRL/ECBDRL.xaa.pdbqt.gz -O EC/BDRL/ECBDRL.xaa.pdbqt.gz
mkdir -pv EC/BDRM && wget http://files.docking.org/3D/EC/BDRM/ECBDRM.xaa.pdbqt.gz -O EC/BDRM/ECBDRM.xaa.pdbqt.gz
mkdir -pv EC/BDRN && wget http://files.docking.org/3D/EC/BDRN/ECBDRN.xaa.pdbqt.gz -O EC/BDRN/ECBDRN.xaa.pdbqt.gz
mkdir -pv EC/BDRN && wget http://files.docking.org/3D/EC/BDRN/ECBDRN.xab.pdbqt.gz -O EC/BDRN/ECBDRN.xab.pdbqt.gz
mkdir -pv EC/BDRO && wget http://files.docking.org/3D/EC/BDRO/ECBDRO.xaa.pdbqt.gz -O EC/BDRO/ECBDRO.xaa.pdbqt.gz
mkdir -pv EC/BDRP && wget http://files.docking.org/3D/EC/BDRP/ECBDRP.xaa.pdbqt.gz -O EC/BDRP/ECBDRP.xaa.pdbqt.gz
mkdir -pv EC/CAML && wget http://files.docking.org/3D/EC/CAML/ECCAML.xaa.pdbqt.gz -O EC/CAML/ECCAML.xaa.pdbqt.gz
mkdir -pv EC/CAMM && wget http://files.docking.org/3D/EC/CAMM/ECCAMM.xaa.pdbqt.gz -O EC/CAMM/ECCAMM.xaa.pdbqt.gz
mkdir -pv EC/CAMN && wget http://files.docking.org/3D/EC/CAMN/ECCAMN.xaa.pdbqt.gz -O EC/CAMN/ECCAMN.xaa.pdbqt.gz
mkdir -pv EC/CAMO && wget http://files.docking.org/3D/EC/CAMO/ECCAMO.xaa.pdbqt.gz -O EC/CAMO/ECCAMO.xaa.pdbqt.gz
mkdir -pv EC/CAMP && wget http://files.docking.org/3D/EC/CAMP/ECCAMP.xaa.pdbqt.gz -O EC/CAMP/ECCAMP.xaa.pdbqt.gz
mkdir -pv EC/CARL && wget http://files.docking.org/3D/EC/CARL/ECCARL.xaa.pdbqt.gz -O EC/CARL/ECCARL.xaa.pdbqt.gz
mkdir -pv EC/CARM && wget http://files.docking.org/3D/EC/CARM/ECCARM.xaa.pdbqt.gz -O EC/CARM/ECCARM.xaa.pdbqt.gz
mkdir -pv EC/CARN && wget http://files.docking.org/3D/EC/CARN/ECCARN.xaa.pdbqt.gz -O EC/CARN/ECCARN.xaa.pdbqt.gz
mkdir -pv EC/CARO && wget http://files.docking.org/3D/EC/CARO/ECCARO.xaa.pdbqt.gz -O EC/CARO/ECCARO.xaa.pdbqt.gz
mkdir -pv EC/CARP && wget http://files.docking.org/3D/EC/CARP/ECCARP.xaa.pdbqt.gz -O EC/CARP/ECCARP.xaa.pdbqt.gz
mkdir -pv EC/CBML && wget http://files.docking.org/3D/EC/CBML/ECCBML.xaa.pdbqt.gz -O EC/CBML/ECCBML.xaa.pdbqt.gz
mkdir -pv EC/CBMM && wget http://files.docking.org/3D/EC/CBMM/ECCBMM.xaa.pdbqt.gz -O EC/CBMM/ECCBMM.xaa.pdbqt.gz
mkdir -pv EC/CBMN && wget http://files.docking.org/3D/EC/CBMN/ECCBMN.xaa.pdbqt.gz -O EC/CBMN/ECCBMN.xaa.pdbqt.gz
mkdir -pv EC/CBMO && wget http://files.docking.org/3D/EC/CBMO/ECCBMO.xaa.pdbqt.gz -O EC/CBMO/ECCBMO.xaa.pdbqt.gz
mkdir -pv EC/CBMP && wget http://files.docking.org/3D/EC/CBMP/ECCBMP.xaa.pdbqt.gz -O EC/CBMP/ECCBMP.xaa.pdbqt.gz
mkdir -pv EC/CBRL && wget http://files.docking.org/3D/EC/CBRL/ECCBRL.xaa.pdbqt.gz -O EC/CBRL/ECCBRL.xaa.pdbqt.gz
mkdir -pv EC/CBRM && wget http://files.docking.org/3D/EC/CBRM/ECCBRM.xaa.pdbqt.gz -O EC/CBRM/ECCBRM.xaa.pdbqt.gz
mkdir -pv EC/CBRN && wget http://files.docking.org/3D/EC/CBRN/ECCBRN.xaa.pdbqt.gz -O EC/CBRN/ECCBRN.xaa.pdbqt.gz
mkdir -pv EC/CBRO && wget http://files.docking.org/3D/EC/CBRO/ECCBRO.xaa.pdbqt.gz -O EC/CBRO/ECCBRO.xaa.pdbqt.gz
mkdir -pv EC/CBRP && wget http://files.docking.org/3D/EC/CBRP/ECCBRP.xaa.pdbqt.gz -O EC/CBRP/ECCBRP.xaa.pdbqt.gz
mkdir -pv EC/CDML && wget http://files.docking.org/3D/EC/CDML/ECCDML.xaa.pdbqt.gz -O EC/CDML/ECCDML.xaa.pdbqt.gz
mkdir -pv EC/CDMM && wget http://files.docking.org/3D/EC/CDMM/ECCDMM.xaa.pdbqt.gz -O EC/CDMM/ECCDMM.xaa.pdbqt.gz
mkdir -pv EC/CDMN && wget http://files.docking.org/3D/EC/CDMN/ECCDMN.xaa.pdbqt.gz -O EC/CDMN/ECCDMN.xaa.pdbqt.gz
mkdir -pv EC/CDMO && wget http://files.docking.org/3D/EC/CDMO/ECCDMO.xaa.pdbqt.gz -O EC/CDMO/ECCDMO.xaa.pdbqt.gz
mkdir -pv EC/CDMP && wget http://files.docking.org/3D/EC/CDMP/ECCDMP.xaa.pdbqt.gz -O EC/CDMP/ECCDMP.xaa.pdbqt.gz
mkdir -pv EC/CDRL && wget http://files.docking.org/3D/EC/CDRL/ECCDRL.xaa.pdbqt.gz -O EC/CDRL/ECCDRL.xaa.pdbqt.gz
mkdir -pv EC/CDRM && wget http://files.docking.org/3D/EC/CDRM/ECCDRM.xaa.pdbqt.gz -O EC/CDRM/ECCDRM.xaa.pdbqt.gz
mkdir -pv EC/CDRN && wget http://files.docking.org/3D/EC/CDRN/ECCDRN.xaa.pdbqt.gz -O EC/CDRN/ECCDRN.xaa.pdbqt.gz
mkdir -pv EC/CDRO && wget http://files.docking.org/3D/EC/CDRO/ECCDRO.xaa.pdbqt.gz -O EC/CDRO/ECCDRO.xaa.pdbqt.gz
mkdir -pv EC/CDRP && wget http://files.docking.org/3D/EC/CDRP/ECCDRP.xaa.pdbqt.gz -O EC/CDRP/ECCDRP.xaa.pdbqt.gz
mkdir -pv EC/EAML && wget http://files.docking.org/3D/EC/EAML/ECEAML.xaa.pdbqt.gz -O EC/EAML/ECEAML.xaa.pdbqt.gz
mkdir -pv EC/EAMM && wget http://files.docking.org/3D/EC/EAMM/ECEAMM.xaa.pdbqt.gz -O EC/EAMM/ECEAMM.xaa.pdbqt.gz
mkdir -pv EC/EAMN && wget http://files.docking.org/3D/EC/EAMN/ECEAMN.xaa.pdbqt.gz -O EC/EAMN/ECEAMN.xaa.pdbqt.gz
mkdir -pv EC/EAMO && wget http://files.docking.org/3D/EC/EAMO/ECEAMO.xaa.pdbqt.gz -O EC/EAMO/ECEAMO.xaa.pdbqt.gz
mkdir -pv EC/EAMP && wget http://files.docking.org/3D/EC/EAMP/ECEAMP.xaa.pdbqt.gz -O EC/EAMP/ECEAMP.xaa.pdbqt.gz
mkdir -pv EC/EARL && wget http://files.docking.org/3D/EC/EARL/ECEARL.xaa.pdbqt.gz -O EC/EARL/ECEARL.xaa.pdbqt.gz
mkdir -pv EC/EARM && wget http://files.docking.org/3D/EC/EARM/ECEARM.xaa.pdbqt.gz -O EC/EARM/ECEARM.xaa.pdbqt.gz
mkdir -pv EC/EARN && wget http://files.docking.org/3D/EC/EARN/ECEARN.xaa.pdbqt.gz -O EC/EARN/ECEARN.xaa.pdbqt.gz
mkdir -pv EC/EARO && wget http://files.docking.org/3D/EC/EARO/ECEARO.xaa.pdbqt.gz -O EC/EARO/ECEARO.xaa.pdbqt.gz
mkdir -pv EC/EARP && wget http://files.docking.org/3D/EC/EARP/ECEARP.xaa.pdbqt.gz -O EC/EARP/ECEARP.xaa.pdbqt.gz
mkdir -pv EC/EBML && wget http://files.docking.org/3D/EC/EBML/ECEBML.xaa.pdbqt.gz -O EC/EBML/ECEBML.xaa.pdbqt.gz
mkdir -pv EC/EBMM && wget http://files.docking.org/3D/EC/EBMM/ECEBMM.xaa.pdbqt.gz -O EC/EBMM/ECEBMM.xaa.pdbqt.gz
mkdir -pv EC/EBMN && wget http://files.docking.org/3D/EC/EBMN/ECEBMN.xaa.pdbqt.gz -O EC/EBMN/ECEBMN.xaa.pdbqt.gz
mkdir -pv EC/EBMO && wget http://files.docking.org/3D/EC/EBMO/ECEBMO.xaa.pdbqt.gz -O EC/EBMO/ECEBMO.xaa.pdbqt.gz
mkdir -pv EC/EBMP && wget http://files.docking.org/3D/EC/EBMP/ECEBMP.xaa.pdbqt.gz -O EC/EBMP/ECEBMP.xaa.pdbqt.gz
mkdir -pv EC/EBRL && wget http://files.docking.org/3D/EC/EBRL/ECEBRL.xaa.pdbqt.gz -O EC/EBRL/ECEBRL.xaa.pdbqt.gz
mkdir -pv EC/EBRM && wget http://files.docking.org/3D/EC/EBRM/ECEBRM.xaa.pdbqt.gz -O EC/EBRM/ECEBRM.xaa.pdbqt.gz
mkdir -pv EC/EBRN && wget http://files.docking.org/3D/EC/EBRN/ECEBRN.xaa.pdbqt.gz -O EC/EBRN/ECEBRN.xaa.pdbqt.gz
mkdir -pv EC/EBRO && wget http://files.docking.org/3D/EC/EBRO/ECEBRO.xaa.pdbqt.gz -O EC/EBRO/ECEBRO.xaa.pdbqt.gz
mkdir -pv EC/EBRP && wget http://files.docking.org/3D/EC/EBRP/ECEBRP.xaa.pdbqt.gz -O EC/EBRP/ECEBRP.xaa.pdbqt.gz
mkdir -pv EC/EDML && wget http://files.docking.org/3D/EC/EDML/ECEDML.xaa.pdbqt.gz -O EC/EDML/ECEDML.xaa.pdbqt.gz
mkdir -pv EC/EDMM && wget http://files.docking.org/3D/EC/EDMM/ECEDMM.xaa.pdbqt.gz -O EC/EDMM/ECEDMM.xaa.pdbqt.gz
mkdir -pv EC/EDMN && wget http://files.docking.org/3D/EC/EDMN/ECEDMN.xaa.pdbqt.gz -O EC/EDMN/ECEDMN.xaa.pdbqt.gz
mkdir -pv EC/EDMN && wget http://files.docking.org/3D/EC/EDMN/ECEDMN.xab.pdbqt.gz -O EC/EDMN/ECEDMN.xab.pdbqt.gz
mkdir -pv EC/EDMO && wget http://files.docking.org/3D/EC/EDMO/ECEDMO.xaa.pdbqt.gz -O EC/EDMO/ECEDMO.xaa.pdbqt.gz
mkdir -pv EC/EDMO && wget http://files.docking.org/3D/EC/EDMO/ECEDMO.xab.pdbqt.gz -O EC/EDMO/ECEDMO.xab.pdbqt.gz
mkdir -pv EC/EDMO && wget http://files.docking.org/3D/EC/EDMO/ECEDMO.xac.pdbqt.gz -O EC/EDMO/ECEDMO.xac.pdbqt.gz
mkdir -pv EC/EDMP && wget http://files.docking.org/3D/EC/EDMP/ECEDMP.xaa.pdbqt.gz -O EC/EDMP/ECEDMP.xaa.pdbqt.gz
mkdir -pv EC/EDRL && wget http://files.docking.org/3D/EC/EDRL/ECEDRL.xaa.pdbqt.gz -O EC/EDRL/ECEDRL.xaa.pdbqt.gz
mkdir -pv EC/EDRM && wget http://files.docking.org/3D/EC/EDRM/ECEDRM.xaa.pdbqt.gz -O EC/EDRM/ECEDRM.xaa.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xaa.pdbqt.gz -O EC/EDRN/ECEDRN.xaa.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xab.pdbqt.gz -O EC/EDRN/ECEDRN.xab.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xac.pdbqt.gz -O EC/EDRN/ECEDRN.xac.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xad.pdbqt.gz -O EC/EDRN/ECEDRN.xad.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xae.pdbqt.gz -O EC/EDRN/ECEDRN.xae.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xaf.pdbqt.gz -O EC/EDRN/ECEDRN.xaf.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xag.pdbqt.gz -O EC/EDRN/ECEDRN.xag.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xah.pdbqt.gz -O EC/EDRN/ECEDRN.xah.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xai.pdbqt.gz -O EC/EDRN/ECEDRN.xai.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xaj.pdbqt.gz -O EC/EDRN/ECEDRN.xaj.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xak.pdbqt.gz -O EC/EDRN/ECEDRN.xak.pdbqt.gz
mkdir -pv EC/EDRN && wget http://files.docking.org/3D/EC/EDRN/ECEDRN.xal.pdbqt.gz -O EC/EDRN/ECEDRN.xal.pdbqt.gz
mkdir -pv EC/EDRO && wget http://files.docking.org/3D/EC/EDRO/ECEDRO.xaa.pdbqt.gz -O EC/EDRO/ECEDRO.xaa.pdbqt.gz
mkdir -pv EC/EDRO && wget http://files.docking.org/3D/EC/EDRO/ECEDRO.xab.pdbqt.gz -O EC/EDRO/ECEDRO.xab.pdbqt.gz
mkdir -pv EC/EDRO && wget http://files.docking.org/3D/EC/EDRO/ECEDRO.xac.pdbqt.gz -O EC/EDRO/ECEDRO.xac.pdbqt.gz
mkdir -pv EC/EDRP && wget http://files.docking.org/3D/EC/EDRP/ECEDRP.xaa.pdbqt.gz -O EC/EDRP/ECEDRP.xaa.pdbqt.gz
mkdir -pv FC/AAML && wget http://files.docking.org/3D/FC/AAML/FCAAML.xaa.pdbqt.gz -O FC/AAML/FCAAML.xaa.pdbqt.gz
mkdir -pv FC/AAMM && wget http://files.docking.org/3D/FC/AAMM/FCAAMM.xaa.pdbqt.gz -O FC/AAMM/FCAAMM.xaa.pdbqt.gz
mkdir -pv FC/AAMN && wget http://files.docking.org/3D/FC/AAMN/FCAAMN.xaa.pdbqt.gz -O FC/AAMN/FCAAMN.xaa.pdbqt.gz
mkdir -pv FC/AAMO && wget http://files.docking.org/3D/FC/AAMO/FCAAMO.xaa.pdbqt.gz -O FC/AAMO/FCAAMO.xaa.pdbqt.gz
mkdir -pv FC/AAMP && wget http://files.docking.org/3D/FC/AAMP/FCAAMP.xaa.pdbqt.gz -O FC/AAMP/FCAAMP.xaa.pdbqt.gz